import { ClassUtils } from "../utils/ClassUtils";
import { AreaMask } from "./AreaMask";
import { NavAgent } from "./Component/NavAgent";
import { NavMeshModifierVolume } from "./Component/NavMeshModifierVolume";
import { NavMeshSurface } from "./Component/NavMeshSurface";
import { NavMeshModifileSurface } from "./Component/NavMeshModifileSurface";
import { NavMeshLink } from "./Component/NavMeshLink";
import { NavMeshObstacles } from "./Component/NavMeshObstacles";
import { NavMesh } from "./NavMesh";
import { NavMeshGrid } from "./NavMeshGrid";
import { NavigationManager } from "./NavigationManager";
import { NavigationUtils } from "./NavigationUtils";
import { RecastConfig } from "./RecastConfig";

let c = ClassUtils.regClass;
c("NavAgent", NavAgent);
c("NavigationUtils", NavigationUtils);
c("NavMeshSurface", NavMeshSurface);
c("NavigationManager", NavigationManager);
c("NavMesh", NavMesh);
c("NavMeshGrid", NavMeshGrid);
c("RecastConfig", RecastConfig);
c("NavMeshSurface", NavMeshSurface);
c("NavMeshModifileSurface", NavMeshModifileSurface);
c("NavMeshLink", NavMeshLink);
c("NavMeshObstacles", NavMeshObstacles);
c("AreaMask", AreaMask);
c("NavMeshModifierVolume", NavMeshModifierVolume);
