import { Physics3DColliderShape } from "./Physics3DColliderShape";
import { Laya3D } from "../../../../Laya3D";
import { EPhysicsCapable } from "../../../Physics3D/physicsEnum/EPhycisCapable";
import { ICompoundColliderShape } from "../../../Physics3D/interface/Shape/ICompoundColliderShape";
import { Quaternion } from "../../../maths/Quaternion";
import { Matrix4x4 } from "../../../maths/Matrix4x4";
import { Vector3 } from "../../../maths/Vector3";
import { MeshFilter } from "../../core/MeshFilter";
import { Sprite3D } from "../../core/Sprite3D";
import { Mesh } from "../../resource/models/Mesh";
import { PhysicsColliderComponent } from "../PhysicsColliderComponent";
import { Rigidbody3D } from "../Rigidbody3D";
import { BoxColliderShape } from "./BoxColliderShape";
import { CapsuleColliderShape } from "./CapsuleColliderShape";
import { ConeColliderShape } from "./ConeColliderShape";
import { CylinderColliderShape } from "./CylinderColliderShape";
import { SphereColliderShape } from "./SphereColliderShape";

type AutoColliderShapeType = "Box" | "Sphere" | "Capsule" | "Cylinder" | "Cone";

interface AutoColliderSource {
    node: Sprite3D;
    mesh: Mesh;
    type: AutoColliderShapeType;
}

interface CompoundChildShape {
    shape: Physics3DColliderShape;
    rotation: Quaternion;
    autoGenerated: boolean;
}

/**
 * @en use to create compound collider.
 * @zh 用于创建组合碰撞器。
 */
export class CompoundColliderShape extends Physics3DColliderShape {
    /** The child container recognized when automatic detection is enabled. */
    static readonly AUTO_COLLIDER_CONTAINER_NAME: string = "__Colliders";

    /**@internal */
    _shape: ICompoundColliderShape;

    /**@internal */
    private _children: CompoundChildShape[] = [];

    /**@internal */
    private _autoDetectChildShapes: boolean = false;

    /**
     * @en Whether to automatically create child shapes from meshes under the `__Colliders` child node.
     * @zh 是否自动识别直属 `__Colliders` 节点下的网格并创建组合碰撞子形状。
     */
    get autoDetectChildShapes(): boolean {
        return this._autoDetectChildShapes;
    }

    set autoDetectChildShapes(value: boolean) {
        if (this._autoDetectChildShapes === value)
            return;
        this._autoDetectChildShapes = value;
        if (value && this.physicsComponent)
            this.rebuildAutoDetectedChildShapes();
    }

    get physicsComponent(): PhysicsColliderComponent {
        return super.physicsComponent;
    }

    set physicsComponent(value: PhysicsColliderComponent) {
        if (super.physicsComponent === value)
            return;
        super.physicsComponent = value;
        this._shape && this._shape.setShapeData(value);
        if (value && this._autoDetectChildShapes)
            this.rebuildAutoDetectedChildShapes();
    }

    /**
     * @en create a new instance of CompoundColliderShape.
     * @zh 创建一个新的组合碰撞形状实例。
     */
    constructor() {
        super();
    }

    protected _createShape(): void {
        if (Laya3D.PhysicsCreateUtil.getPhysicsCapable(EPhysicsCapable.Physics_CompoundColliderShape)) {
            this._shape = Laya3D.PhysicsCreateUtil.createCompoundShape();
        } else {
            console.error("CompoundColliderShape: cannot enable CompoundColliderShape");
        }
    }

    /**
     * @en set the physics shape array.
     * @zh 设置物理形状数组。
     */
    public set shapes(value: Physics3DColliderShape[]) {
        this.clearChildShape();
        for (let i = 0; i < value.length; i++)
            this.addChildShape(value[i]);
    }

    public get shapes(): Physics3DColliderShape[] {
        return this._children.map(child => child.shape);
    }

    /**
     * @en add a child collider shape.
     * @param shape The shape to be added as a child collider.
     * @zh 添加一个子碰撞器形状。
     * @param shape 子碰撞器形状。
     */
    addChildShape(shape: Physics3DColliderShape): void {
        this._addChildShape(shape, null, false);
    }

    private _addChildShape(shape: Physics3DColliderShape, localRotation: Quaternion, autoGenerated: boolean): void {
        if (shape instanceof CompoundColliderShape) {
            console.warn("CompoundColliderShape: cannot add a CompoundColliderShape as a child shape.");
            return;
        }
        const rotation = localRotation ? localRotation.clone() : new Quaternion();
        this._shape && this._shape.setShapeData(this.physicsComponent);
        this._shape && this._shape.addChildShape(shape.shape, rotation);
        this._children.push({ shape, rotation, autoGenerated });
    }

    /**
     * @en remove a child collider shape.
     * @param shape The shape to be removed from the child collider.
     * @zh 移除一个子碰撞器形状。
     * @param shape 子碰撞器形状。
     */
    removeChildShape(shape: Physics3DColliderShape): void {
        if (shape instanceof CompoundColliderShape) {
            console.warn("CompoundColliderShape: cannot remove a CompoundColliderShape as a child shape.");
            return;
        }
        const index = this._children.findIndex(child => child.shape === shape);
        if (index < 0)
            return;
        this._removeChildShapeAt(index, false);
    }

    /**
     * @en clear the child collider shape.
     * @zh 清空子碰撞器形状。
     */
    clearChildShape(): void {
        while (this._children.length > 0)
            this._removeChildShapeAt(0, false);
    }

    private _removeChildShapeAt(index: number, destroy: boolean): void {
        const child = this._children[index];
        this._shape && this._shape.removeChildShape(child.shape.shape, index);
        this._children.splice(index, 1);
        destroy && child.shape.destroy();
    }

    /**
     * @en get the child shape count.
     * @zh 获取子形状数量。
     */
    getChildShapeCount(): number {
        return this._children.length;
    }

    /**
     * @en Rebuilds child shapes from meshes under the owner's `__Colliders` child node.
     * @returns Whether at least one child shape was generated successfully.
     * @zh 根据所属节点直属 `__Colliders` 节点下的网格重新生成子形状。
     * @returns 是否成功生成了至少一个子形状。
     */
    rebuildAutoDetectedChildShapes(): boolean {
        if (!this._shape) {
            console.warn("CompoundColliderShape: cannot rebuild a destroyed or unsupported compound shape.");
            return false;
        }
        const component = this.physicsComponent;
        const root = component && component.owner;
        if (!root) {
            console.warn("CompoundColliderShape: automatic detection requires an owner node.");
            return false;
        }

        const container = this._findAutoColliderContainer(root);
        if (!container) {
            console.warn(`CompoundColliderShape: cannot find child node '${CompoundColliderShape.AUTO_COLLIDER_CONTAINER_NAME}'.`);
            return false;
        }

        const sources: AutoColliderSource[] = [];
        this._collectAutoColliderSources(container, sources, true);
        if (sources.length === 0) {
            console.warn(`CompoundColliderShape: '${CompoundColliderShape.AUTO_COLLIDER_CONTAINER_NAME}' contains no valid MeshFilter.`);
            return false;
        }

        const rootInverse = new Matrix4x4();
        root.transform.worldMatrix.invert(rootInverse);
        const generatedChildren: CompoundChildShape[] = [];

        try {
            for (let i = 0, n = sources.length; i < n; i++) {
                const result = this._createAutoColliderShape(sources[i], rootInverse);
                generatedChildren.push({ ...result, autoGenerated: true });
            }
        } catch (error) {
            for (let i = 0, n = generatedChildren.length; i < n; i++)
                generatedChildren[i].shape.destroy();
            console.error("CompoundColliderShape: failed to create automatically detected child shapes.", error);
            return false;
        }

        for (let i = this._children.length - 1; i >= 0; i--) {
            if (this._children[i].autoGenerated)
                this._removeChildShapeAt(i, true);
        }
        for (let i = 0, n = generatedChildren.length; i < n; i++) {
            const child = generatedChildren[i];
            this._addChildShape(child.shape, child.rotation, true);
        }
        this._refreshAfterAutoDetection();
        return true;
    }

    private _refreshAfterAutoDetection(): void {
        const component = this.physicsComponent;
        if (component instanceof Rigidbody3D && component.colliderShape === this) {
            component.mass = component.mass;
            component.wakeUp();
        }
    }

    private _findAutoColliderContainer(root: Sprite3D): Sprite3D {
        for (let i = 0, n = root.numChildren; i < n; i++) {
            const child = root.getChildAt(i);
            if (child instanceof Sprite3D && child.name === CompoundColliderShape.AUTO_COLLIDER_CONTAINER_NAME)
                return child;
        }
        return null;
    }

    private _collectAutoColliderSources(node: Sprite3D, output: AutoColliderSource[], excludeSelf: boolean): void {
        if (!excludeSelf) {
            const mesh = node.getComponent(MeshFilter)?.sharedMesh;
            if (mesh)
                output.push({ node, mesh, type: this._getAutoColliderShapeType(node.name) });
        }
        for (let i = 0, n = node.numChildren; i < n; i++) {
            const child = node.getChildAt(i);
            if (child instanceof Sprite3D)
                this._collectAutoColliderSources(child, output, false);
        }
    }

    private _getAutoColliderShapeType(name: string): AutoColliderShapeType {
        const lowerName = name.toLowerCase();
        if (lowerName.startsWith("col_sphere_")) return "Sphere";
        if (lowerName.startsWith("col_capsule_")) return "Capsule";
        if (lowerName.startsWith("col_cylinder_")) return "Cylinder";
        if (lowerName.startsWith("col_cone_")) return "Cone";
        return "Box";
    }

    private _createAutoColliderShape(source: AutoColliderSource, rootInverse: Matrix4x4): { shape: Physics3DColliderShape, rotation: Quaternion } {
        const nodeToRoot = new Matrix4x4();
        Matrix4x4.multiply(rootInverse, source.node.transform.worldMatrix, nodeToRoot);

        const translation = new Vector3();
        const rotation = new Quaternion();
        const scale = new Vector3();
        if (!nodeToRoot.decomposeTransRotScale(translation, rotation, scale))
            throw new Error(`${source.node.name}: relative transform cannot be decomposed.`);

        const scaleX = Math.abs(scale.x);
        const scaleY = Math.abs(scale.y);
        const scaleZ = Math.abs(scale.z);
        if (scaleX < 0.00001 || scaleY < 0.00001 || scaleZ < 0.00001)
            throw new Error(`${source.node.name}: zero scale is not supported.`);

        const extent = source.mesh.bounds.getExtent();
        const position = new Vector3();
        Vector3.transformCoordinate(source.mesh.bounds.getCenter(), nodeToRoot, position);
        let shape: Physics3DColliderShape;

        switch (source.type) {
            case "Sphere": {
                this._requireShapeCapability(EPhysicsCapable.Physics_SphereColliderShape, source);
                const maxScale = Math.max(scaleX, scaleY, scaleZ);
                const minScale = Math.min(scaleX, scaleY, scaleZ);
                if ((maxScale - minScale) / maxScale > 0.01)
                    throw new Error(`${source.node.name}: sphere requires uniform scale.`);
                const radius = Math.max(extent.x, extent.y, extent.z) * maxScale;
                shape = new SphereColliderShape(Math.max(radius, 0.0001));
                break;
            }
            case "Capsule":
            case "Cylinder":
            case "Cone": {
                const capability = source.type === "Capsule" ? EPhysicsCapable.Physics_CapsuleColliderShape :
                    source.type === "Cylinder" ? EPhysicsCapable.Physics_CylinderColliderShape : EPhysicsCapable.Physics_ConeColliderShape;
                this._requireShapeCapability(capability, source);
                const diameterX = extent.x * 2 * scaleX;
                const diameterZ = extent.z * 2 * scaleZ;
                const diameter = Math.max(diameterX, diameterZ);
                if (diameter < 0.0001 || Math.abs(diameterX - diameterZ) / diameter > 0.01)
                    throw new Error(`${source.node.name}: ${source.type} requires an equally scaled X/Z cross section.`);
                const radius = Math.max(diameter * 0.5, 0.0001);
                const height = Math.max(extent.y * 2 * scaleY, 0.0001);
                if (source.type === "Capsule")
                    shape = new CapsuleColliderShape(radius, Math.max(height, radius * 2), Physics3DColliderShape.SHAPEORIENTATION_UPY);
                else if (source.type === "Cylinder")
                    shape = new CylinderColliderShape(radius, height, Physics3DColliderShape.SHAPEORIENTATION_UPY);
                else
                    shape = new ConeColliderShape(radius, height, Physics3DColliderShape.SHAPEORIENTATION_UPY);
                break;
            }
            default:
                this._requireShapeCapability(EPhysicsCapable.Physics_BoxColliderShape, source);
                shape = new BoxColliderShape(
                    Math.max(extent.x * 2 * scaleX, 0.0001),
                    Math.max(extent.y * 2 * scaleY, 0.0001),
                    Math.max(extent.z * 2 * scaleZ, 0.0001)
                );
                break;
        }

        shape.localOffset = position;
        return { shape, rotation };
    }

    private _requireShapeCapability(capability: EPhysicsCapable, source: AutoColliderSource): void {
        if (!Laya3D.PhysicsCreateUtil.getPhysicsCapable(capability))
            throw new Error(`${source.node.name}: ${source.type} is not supported by the current physics backend.`);
    }

    /**
     * @en clone the data to the destination node.
     * @zh 将数据克隆到目标节点。
     */
    cloneTo(destObject: CompoundColliderShape): void {
        destObject.clearChildShape();
        for (let i = 0, n = this._children.length; i < n; i++) {
            const child = this._children[i];
            destObject._addChildShape(child.shape.clone(), child.rotation, child.autoGenerated);
        }
        destObject._autoDetectChildShapes = this._autoDetectChildShapes;
    }

    /**
     * @en clone the data to the destination node.
     * @zh 将数据克隆到目标节点。
     */
    clone() {
        var dest: CompoundColliderShape = new CompoundColliderShape();
        this.cloneTo(dest);
        return dest;
    }

    /**
     * @en destroy the instance.
     * @zh 销毁实例。
     */
    destroy(): void {
        super.destroy();
        for (let i = 0, n = this._children.length; i < n; i++)
            this._children[i].shape.destroy();
        this._children.length = 0;
    }
}

