import { ClassUtils } from "../utils/ClassUtils";
import { HTMLBrElement } from "./dom/HTMLBrElement";
import { HTMLDivElement } from "./dom/HTMLDivElement";
import { HTMLDivParser } from "./dom/HTMLDivParser";
import { HTMLDocument } from "./dom/HTMLDocument";
import { HTMLElement } from "./dom/HTMLElement";
import { HTMLHitRect } from "./dom/HTMLHitRect";
import { HTMLIframeElement } from "./dom/HTMLIframeElement";
import { HTMLImageElement } from "./dom/HTMLImageElement";
import { HTMLLinkElement } from "./dom/HTMLLinkElement";
import { HTMLStyleElement } from "./dom/HTMLStyleElement";
import { HTMLExtendStyle } from "./utils/HTMLExtendStyle";
import { HTMLParse } from "./utils/HTMLParse";
import { HTMLStyle } from "./utils/HTMLStyle";
import { Layout } from "./utils/Layout";
import { LayoutLine } from "./utils/LayoutLine";

let c = ClassUtils.regClass;
c("Laya.HTMLBrElement", HTMLBrElement);
c("Laya.HTMLDivElement", HTMLDivElement);
c("Laya.HTMLDivParser", HTMLDivParser);
c("Laya.HTMLDocument", HTMLDocument);
c("Laya.HTMLElement", HTMLElement);
c("Laya.HTMLHitRect", HTMLHitRect);
c("Laya.HTMLIframeElement", HTMLIframeElement);
c("Laya.HTMLImageElement", HTMLImageElement);
c("Laya.HTMLLinkElement", HTMLLinkElement);
c("Laya.HTMLStyleElement", HTMLStyleElement);
c("Laya.HTMLExtendStyle", HTMLExtendStyle);
c("Laya.HTMLParse", HTMLParse);
c("Laya.HTMLStyle", HTMLStyle);
c("Laya.Layout", Layout);
c("Laya.LayoutLine", LayoutLine);
c('div', HTMLDivParser);
c('p', HTMLElement);
c('img', HTMLImageElement);
c('span', HTMLElement);
c('br', HTMLBrElement);
c('style', HTMLStyleElement);
c('font', HTMLElement);
c('a', HTMLElement);
c('#text', HTMLElement);
c('link', HTMLLinkElement);
