import { ClassUtils } from "../utils/ClassUtils";
import { BoxCollider } from "./BoxCollider";
import { ChainCollider } from "./ChainCollider";
import { CircleCollider } from "./CircleCollider";
import { ColliderBase } from "./ColliderBase";
import { EdgeCollider } from "./EdgeCollider";
import { DistanceJoint } from "./joint/DistanceJoint";
import { GearJoint } from "./joint/GearJoint";
import { JointBase } from "./joint/JointBase";
import { MotorJoint } from "./joint/MotorJoint";
import { MouseJoint } from "./joint/MouseJoint";
import { PrismaticJoint } from "./joint/PrismaticJoint";
import { PulleyJoint } from "./joint/PulleyJoint";
import { RevoluteJoint } from "./joint/RevoluteJoint";
import { WeldJoint } from "./joint/WeldJoint";
import { WheelJoint } from "./joint/WheelJoint";
import { Physics } from "./Physics";
import { PhysicsDebugDraw } from "./PhysicsDebugDraw";
import { PolygonCollider } from "./PolygonCollider";
import { RigidBody } from "./RigidBody";

let c = ClassUtils.regClass;
c("Laya.Physics", Physics);
c("Laya.PhysicsDebugDraw", PhysicsDebugDraw);
c("Laya.ColliderBase", ColliderBase);
c("Laya.BoxCollider", BoxCollider);
c("Laya.ChainCollider", ChainCollider);
c("Laya.CircleCollider", CircleCollider);
c("Laya.EdgeCollider", EdgeCollider);
c("Laya.PolygonCollider", PolygonCollider);
c("Laya.RigidBody", RigidBody);
c("Laya.JointBase", JointBase);
c("Laya.DistanceJoint", DistanceJoint);
c("Laya.GearJoint", GearJoint);
c("Laya.MotorJoint", MotorJoint);
c("Laya.MouseJoint", MouseJoint);
c("Laya.PrismaticJoint", PrismaticJoint);
c("Laya.PulleyJoint", PulleyJoint);
c("Laya.RevoluteJoint", RevoluteJoint);
c("Laya.WeldJoint", WeldJoint);
c("Laya.WheelJoint", WheelJoint);