if (window.conch && window.physx) {
	window.PHYSX = function(initialMemory, interactive) {
	var fake = {};
	fake.then = (complete) => {
		return complete(window.physx);
	};
	return fake;
	};
}
else {
var PHYSX = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(PHYSX) {
  PHYSX = PHYSX || {};


var g;g||(g=typeof PHYSX !== 'undefined' ? PHYSX : {});var aa=Object.assign,ba,ca;g.ready=new Promise(function(a,b){ba=a;ca=b});var da=aa({},g),ea=(a,b)=>{throw b;},ha="object"===typeof window,q="function"===typeof importScripts,ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,v="",ja,ka,la,fs,ma,na;
if(ia)v=q?require("path").dirname(v)+"/":__dirname+"/",na=function(){ma||(fs=require("fs"),ma=require("path"))},ja=function(a,b){na();a=ma.normalize(a);return fs.readFileSync(a,b?null:"utf8")},la=function(a){a=ja(a,!0);a.buffer||(a=new Uint8Array(a));return a},ka=function(a,b,c){na();a=ma.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(a){if(!(a instanceof oa))throw a;
}),process.on("unhandledRejection",function(a){throw a;}),ea=(a,b)=>{if(noExitRuntime||0<pa)throw process.exitCode=a,b;b instanceof oa||x("exiting due to exception: "+b);process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ha||q)q?v=self.location.href:"undefined"!==typeof document&&document.currentScript&&(v=document.currentScript.src),_scriptDir&&(v=_scriptDir),0!==v.indexOf("blob:")?v=v.substr(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1):v="",ja=function(a){var b=new XMLHttpRequest;
b.open("GET",a,!1);b.send(null);return b.responseText},q&&(la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var qa=g.print||console.log.bind(console),x=g.printErr||console.warn.bind(console);aa(g,da);da=null;
g.quit&&(ea=g.quit);var y;g.wasmBinary&&(y=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&z("no native wasm support detected");var B,ra=!1,sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ta(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function ua(a,b,c){var d=C;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0}}var va="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function wa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&xa[c];)++c;c<<=1;if(32<c-a&&va)return va.decode(C.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=D[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function ya(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d}function za(a){return 2*a.length}
function Aa(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function Ba(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}
function Ca(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var G,Da,C,D,xa,E,H,Ea,Fa;function Ga(a){G=a;g.HEAP8=Da=new Int8Array(a);g.HEAP16=D=new Int16Array(a);g.HEAP32=E=new Int32Array(a);g.HEAPU8=C=new Uint8Array(a);g.HEAPU16=xa=new Uint16Array(a);g.HEAPU32=H=new Uint32Array(a);g.HEAPF32=Ea=new Float32Array(a);g.HEAPF64=Fa=new Float64Array(a)}var Ha=g.INITIAL_MEMORY||16777216;
g.wasmMemory?B=g.wasmMemory:B=new WebAssembly.Memory({initial:Ha/65536,maximum:32768});B&&(G=B.buffer);Ha=G.byteLength;Ga(G);var Ia,Ja=[],Ka=[],La=[],pa=0;function Ma(){var a=g.preRun.shift();Ja.unshift(a)}var I=0,Na=null,Oa=null;g.preloadedImages={};g.preloadedAudios={};function z(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";x(a);ra=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ca(a);throw a;}
function Pa(){return J.startsWith("data:application/octet-stream;base64,")}var J;J="physx.release.wasm";if(!Pa()){var Qa=J;J=g.locateFile?g.locateFile(Qa,v):v+Qa}function Ra(){var a=J;try{if(a==J&&y)return new Uint8Array(y);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Sa(){if(!y&&(ha||q)){if("function"===typeof fetch&&!J.startsWith("file://"))return fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Ra()});if(ka)return new Promise(function(a,b){ka(J,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ra()})}
function Ta(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Ma;"number"===typeof c?void 0===b.ma?Ua(c)():Ua(c)(b.ma):c(void 0===b.ma?null:b.ma)}}}var Va=[];function Ua(a){var b=Va[a];b||(a>=Va.length&&(Va.length=a+1),Va[a]=b=Ia.get(a));return b}function Wa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Xa(a,b){a=Wa(a);return function(){null;return b.apply(this,arguments)}}
var K=[{},{value:void 0},{value:null},{value:!0},{value:!1}],Ya=[];function Za(a){var b=Error,c=Xa(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var M=void 0;function N(a){throw new M(a);}
function $a(a){a||N("Cannot use deleted val. handle = "+a);return K[a].value}function ab(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ya.length?Ya.pop():K.length;K[b]={pa:1,value:a};return b}}var bb=void 0,cb=void 0;function O(a){for(var b="";C[a];)b+=cb[C[a++]];return b}var db=[];function eb(){for(;db.length;){var a=db.pop();a.U.ha=!1;a["delete"]()}}var fb=void 0,P={};
function gb(a,b){for(void 0===b&&N("ptr should not be undefined");a.Z;)b=a.ja(b),a=a.Z;return b}var Q={};function hb(a){a=ib(a);var b=O(a);R(a);return b}function jb(a,b){var c=Q[a];void 0===c&&N(b+" has unknown type "+hb(a));return c}function kb(){}var lb=!1;function mb(a){--a.count.value;0===a.count.value&&(a.$?a.ba.ea(a.$):a.X.V.ea(a.W))}
function S(a){if("undefined"===typeof FinalizationGroup)return S=function(b){return b},a;lb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.W?mb(c):console.warn("object already deleted: "+c.W)});S=function(b){lb.register(b,b.U,b.U);return b};kb=function(b){lb.unregister(b.U)};return S(a)}var nb={};function ob(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function pb(a){return this.fromWireType(H[a>>2])}var T={},qb={},rb=void 0;function sb(a){throw new rb(a);}
function U(a,b,c){function d(h){h=c(h);h.length!==a.length&&sb("Mismatched type converter count");for(var m=0;m<a.length;++m)V(a[m],h[m])}a.forEach(function(h){qb[h]=b});var e=Array(b.length),f=[],k=0;b.forEach(function(h,m){Q.hasOwnProperty(h)?e[m]=Q[h]:(f.push(h),T.hasOwnProperty(h)||(T[h]=[]),T[h].push(function(){e[m]=Q[h];++k;k===f.length&&d(e)}))});0===f.length&&d(e)}
function tb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}
function V(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||N('type "'+d+'" must have a positive integer typeid pointer');if(Q.hasOwnProperty(a)){if(c.Da)return;N("Cannot register type '"+d+"' twice")}Q[a]=b;delete qb[a];T.hasOwnProperty(a)&&(b=T[a],delete T[a],b.forEach(function(e){e()}))}function ub(a){N(a.U.X.V.name+" instance already deleted")}function W(){}var vb={};
function wb(a,b,c){if(void 0===a[b].Y){var d=a[b];a[b]=function(){a[b].Y.hasOwnProperty(arguments.length)||N("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Y+")!");return a[b].Y[arguments.length].apply(this,arguments)};a[b].Y=[];a[b].Y[d.ga]=d}}
function xb(a,b,c){g.hasOwnProperty(a)?((void 0===c||void 0!==g[a].Y&&void 0!==g[a].Y[c])&&N("Cannot register public name '"+a+"' twice"),wb(g,a,a),g.hasOwnProperty(c)&&N("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),g[a].Y[c]=b):(g[a]=b,void 0!==c&&(g[a].Na=c))}function yb(a,b,c,d,e,f,k,h){this.name=a;this.constructor=b;this.da=c;this.ea=d;this.Z=e;this.ya=f;this.ja=k;this.wa=h;this.sa=[]}
function zb(a,b,c){for(;b!==c;)b.ja||N("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.ja(a),b=b.Z;return a}function Ab(a,b){if(null===b)return this.na&&N("null is not a valid "+this.name),0;b.U||N('Cannot pass "'+Bb(b)+'" as a '+this.name);b.U.W||N("Cannot pass deleted object as a pointer of type "+this.name);return zb(b.U.W,b.U.X.V,this.V)}
function Cb(a,b){if(null===b){this.na&&N("null is not a valid "+this.name);if(this.la){var c=this.oa();null!==a&&a.push(this.ea,c);return c}return 0}b.U||N('Cannot pass "'+Bb(b)+'" as a '+this.name);b.U.W||N("Cannot pass deleted object as a pointer of type "+this.name);!this.ka&&b.U.X.ka&&N("Cannot convert argument of type "+(b.U.ba?b.U.ba.name:b.U.X.name)+" to parameter type "+this.name);c=zb(b.U.W,b.U.X.V,this.V);if(this.la)switch(void 0===b.U.$&&N("Passing raw pointer to smart pointer is illegal"),
this.Ka){case 0:b.U.ba===this?c=b.U.$:N("Cannot convert argument of type "+(b.U.ba?b.U.ba.name:b.U.X.name)+" to parameter type "+this.name);break;case 1:c=b.U.$;break;case 2:if(b.U.ba===this)c=b.U.$;else{var d=b.clone();c=this.Ga(c,ab(function(){d["delete"]()}));null!==a&&a.push(this.ea,c)}break;default:N("Unsupporting sharing policy")}return c}
function Db(a,b){if(null===b)return this.na&&N("null is not a valid "+this.name),0;b.U||N('Cannot pass "'+Bb(b)+'" as a '+this.name);b.U.W||N("Cannot pass deleted object as a pointer of type "+this.name);b.U.X.ka&&N("Cannot convert argument of type "+b.U.X.name+" to parameter type "+this.name);return zb(b.U.W,b.U.X.V,this.V)}function Eb(a,b,c){if(b===c)return a;if(void 0===c.Z)return null;a=Eb(a,b,c.Z);return null===a?null:c.wa(a)}function Fb(a,b){b=gb(a,b);return P[b]}
function Hb(a,b){b.X&&b.W||sb("makeClassHandle requires ptr and ptrType");!!b.ba!==!!b.$&&sb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return S(Object.create(a,{U:{value:b}}))}function X(a,b,c,d){this.name=a;this.V=b;this.na=c;this.ka=d;this.la=!1;this.ea=this.Ga=this.oa=this.ta=this.Ka=this.Fa=void 0;void 0!==b.Z?this.toWireType=Cb:(this.toWireType=d?Ab:Db,this.aa=null)}
function Ib(a,b,c){g.hasOwnProperty(a)||sb("Replacing nonexistant public symbol");void 0!==g[a].Y&&void 0!==c?g[a].Y[c]=b:(g[a]=b,g[a].ga=c)}function Jb(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=Ua(b).apply(null,c);return d}}
function Y(a,b){a=O(a);var c=a.includes("j")?Jb(a,b):Ua(b);"function"!==typeof c&&N("unknown function pointer with signature "+a+": "+b);return c}var Kb=void 0;function Z(a,b){function c(f){e[f]||Q[f]||(qb[f]?qb[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Kb(a+": "+d.map(hb).join([", "]));}
function Lb(a,b,c,d,e){var f=b.length;2>f&&N("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,h=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].aa){h=!0;break}var m="void"!==b[0].name,l=f-2,n=Array(l),p=[],r=[];return function(){arguments.length!==l&&N("function "+a+" called with "+arguments.length+" arguments, expected "+l+" args!");r.length=0;p.length=k?2:1;p[0]=e;if(k){var u=b[1].toWireType(r,this);p[1]=u}for(var t=0;t<l;++t)n[t]=
b[t+2].toWireType(r,arguments[t]),p.push(n[t]);t=d.apply(null,p);if(h)ob(r);else for(var w=k?1:2;w<b.length;w++){var A=1===w?u:n[w-2];null!==b[w].aa&&b[w].aa(A)}u=m?b[0].fromWireType(t):void 0;return u}}function Mb(a,b){for(var c=[],d=0;d<a;d++)c.push(E[(b>>2)+d]);return c}
function Nb(a,b,c){a instanceof Object||N(c+' with invalid "this": '+a);a instanceof b.V.constructor||N(c+' incompatible with "this" of type '+a.constructor.name);a.U.W||N("cannot call emscripten binding method "+c+" on deleted object");return zb(a.U.W,a.U.X.V,b.V)}function Ob(a){4<a&&0===--K[a].pa&&(K[a]=void 0,Ya.push(a))}
function Pb(a,b,c){switch(b){case 0:return function(d){return this.fromWireType((c?Da:C)[d])};case 1:return function(d){return this.fromWireType((c?D:xa)[d>>1])};case 2:return function(d){return this.fromWireType((c?E:H)[d>>2])};default:throw new TypeError("Unknown integer type: "+a);}}function Bb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Qb(a,b){switch(b){case 2:return function(c){return this.fromWireType(Ea[c>>2])};case 3:return function(c){return this.fromWireType(Fa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Rb(a,b,c){switch(b){case 0:return c?function(d){return Da[d]}:function(d){return C[d]};case 1:return c?function(d){return D[d>>1]}:function(d){return xa[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return H[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Sb={},Tb=[];function Ub(a){var b=Tb.length;Tb.push(a);return b}function Vb(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=jb(E[(b>>2)+d],"parameter "+d);return c}var Wb=[],Xb;
Xb=ia?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var Yb=[null,[],[]];M=g.BindingError=Za("BindingError");g.count_emval_handles=function(){for(var a=0,b=5;b<K.length;++b)void 0!==K[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<K.length;++a)if(void 0!==K[a])return K[a];return null};bb=g.PureVirtualError=Za("PureVirtualError");for(var Zb=Array(256),$b=0;256>$b;++$b)Zb[$b]=String.fromCharCode($b);cb=Zb;g.getInheritedInstanceCount=function(){return Object.keys(P).length};
g.getLiveInheritedInstances=function(){var a=[],b;for(b in P)P.hasOwnProperty(b)&&a.push(P[b]);return a};g.flushPendingDeletes=eb;g.setDelayFunction=function(a){fb=a;db.length&&fb&&fb(eb)};rb=g.InternalError=Za("InternalError");W.prototype.isAliasOf=function(a){if(!(this instanceof W&&a instanceof W))return!1;var b=this.U.X.V,c=this.U.W,d=a.U.X.V;for(a=a.U.W;b.Z;)c=b.ja(c),b=b.Z;for(;d.Z;)a=d.ja(a),d=d.Z;return b===d&&c===a};
W.prototype.clone=function(){this.U.W||ub(this);if(this.U.ia)return this.U.count.value+=1,this;var a=S,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.U;a=a(c.call(b,d,{U:{value:{count:e.count,ha:e.ha,ia:e.ia,W:e.W,X:e.X,$:e.$,ba:e.ba}}}));a.U.count.value+=1;a.U.ha=!1;return a};W.prototype["delete"]=function(){this.U.W||ub(this);this.U.ha&&!this.U.ia&&N("Object already scheduled for deletion");kb(this);mb(this.U);this.U.ia||(this.U.$=void 0,this.U.W=void 0)};W.prototype.isDeleted=function(){return!this.U.W};
W.prototype.deleteLater=function(){this.U.W||ub(this);this.U.ha&&!this.U.ia&&N("Object already scheduled for deletion");db.push(this);1===db.length&&fb&&fb(eb);this.U.ha=!0;return this};X.prototype.za=function(a){this.ta&&(a=this.ta(a));return a};X.prototype.qa=function(a){this.ea&&this.ea(a)};X.prototype.argPackAdvance=8;X.prototype.readValueFromPointer=pb;X.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
X.prototype.fromWireType=function(a){function b(){return this.la?Hb(this.V.da,{X:this.Fa,W:c,ba:this,$:a}):Hb(this.V.da,{X:this,W:a})}var c=this.za(a);if(!c)return this.qa(a),null;var d=Fb(this.V,c);if(void 0!==d){if(0===d.U.count.value)return d.U.W=c,d.U.$=a,d.clone();d=d.clone();this.qa(a);return d}d=this.V.ya(c);d=vb[d];if(!d)return b.call(this);d=this.ka?d.ua:d.pointerType;var e=Eb(c,this.V,d.V);return null===e?b.call(this):this.la?Hb(d.V.da,{X:d,W:e,ba:this,$:a}):Hb(d.V.da,{X:d,W:e})};
Kb=g.UnboundTypeError=Za("UnboundTypeError");
var bc={I:function(a,b,c){a=O(a);b=jb(b,"wrapper");c=$a(c);var d=[].slice,e=b.V,f=e.da,k=e.Z.da,h=e.Z.constructor;a=Xa(a,function(){e.Z.sa.forEach(function(l){if(this[l]===k[l])throw new bb("Pure virtual function "+l+" must be implemented in JavaScript");}.bind(this));Object.defineProperty(this,"__parent",{value:f});this.__construct.apply(this,d.call(arguments))});f.__construct=function(){this===f&&N("Pass correct 'this' to __construct");var l=h.implement.apply(void 0,[this].concat(d.call(arguments)));
kb(l);var n=l.U;l.notifyOnDestruction();n.ia=!0;Object.defineProperties(this,{U:{value:n}});S(this);l=n.W;l=gb(e,l);P.hasOwnProperty(l)?N("Tried to register registered instance: "+l):P[l]=this};f.__destruct=function(){this===f&&N("Pass correct 'this' to __destruct");kb(this);var l=this.U.W;l=gb(e,l);P.hasOwnProperty(l)?delete P[l]:N("Tried to unregister unregistered instance: "+l)};a.prototype=Object.create(f);for(var m in c)a.prototype[m]=c[m];return ab(a)},m:function(a){var b=nb[a];delete nb[a];
var c=b.oa,d=b.ea,e=b.ra,f=e.map(function(k){return k.Ca}).concat(e.map(function(k){return k.Ia}));U([a],f,function(k){var h={};e.forEach(function(m,l){var n=k[l],p=m.Aa,r=m.Ba,u=k[l+e.length],t=m.Ha,w=m.Ja;h[m.xa]={read:function(A){return n.fromWireType(p(r,A))},write:function(A,L){var F=[];t(w,A,u.toWireType(F,L));ob(F)}}});return[{name:b.name,fromWireType:function(m){var l={},n;for(n in h)l[n]=h[n].read(m);d(m);return l},toWireType:function(m,l){for(var n in h)if(!(n in l))throw new TypeError('Missing field:  "'+
n+'"');var p=c();for(n in h)h[n].write(p,l[n]);null!==m&&m.push(d,p);return p},argPackAdvance:8,readValueFromPointer:pb,aa:d}]})},A:function(){},F:function(a,b,c,d,e){var f=tb(c);b=O(b);V(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var h=Da;else if(2===c)h=D;else if(4===c)h=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[k>>f])},aa:null})},c:function(a,b,c,d,e,
f,k,h,m,l,n,p,r){n=O(n);f=Y(e,f);h&&(h=Y(k,h));l&&(l=Y(m,l));r=Y(p,r);var u=Wa(n);xb(u,function(){Z("Cannot construct "+n+" due to unbound types",[d])});U([a,b,c],d?[d]:[],function(t){t=t[0];if(d){var w=t.V;var A=w.da}else A=W.prototype;t=Xa(u,function(){if(Object.getPrototypeOf(this)!==L)throw new M("Use 'new' to construct "+n);if(void 0===F.fa)throw new M(n+" has no accessible constructor");var Gb=F.fa[arguments.length];if(void 0===Gb)throw new M("Tried to invoke ctor of "+n+" with invalid number of parameters ("+
arguments.length+") - expected ("+Object.keys(F.fa).toString()+") parameters instead!");return Gb.apply(this,arguments)});var L=Object.create(A,{constructor:{value:t}});t.prototype=L;var F=new yb(n,t,L,r,w,f,h,l);w=new X(n,F,!0,!1);A=new X(n+"*",F,!1,!1);var fa=new X(n+" const*",F,!1,!0);vb[a]={pointerType:A,ua:fa};Ib(u,t);return[w,A,fa]})},z:function(a,b,c,d,e,f,k){var h=Mb(c,d);b=O(b);f=Y(e,f);U([],[a],function(m){function l(){Z("Cannot call "+n+" due to unbound types",h)}m=m[0];var n=m.name+"."+
b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var p=m.V.constructor;void 0===p[b]?(l.ga=c-1,p[b]=l):(wb(p,b,n),p[b].Y[c-1]=l);U([],h,function(r){r=[r[0],null].concat(r.slice(1));r=Lb(n,r,null,f,k);void 0===p[b].Y?(r.ga=c-1,p[b]=r):p[b].Y[c-1]=r;return[]});return[]})},f:function(a,b,c,d,e,f){0<b||z(void 0);var k=Mb(b,c);e=Y(d,e);U([],[a],function(h){h=h[0];var m="constructor "+h.name;void 0===h.V.fa&&(h.V.fa=[]);if(void 0!==h.V.fa[b-1])throw new M("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+h.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");h.V.fa[b-1]=function(){Z("Cannot construct "+h.name+" due to unbound types",k)};U([],k,function(l){l.splice(1,0,null);h.V.fa[b-1]=Lb(m,l,null,e,f);return[]});return[]})},b:function(a,b,c,d,e,f,k,h){var m=Mb(c,d);b=O(b);f=Y(e,f);U([],[a],function(l){function n(){Z("Cannot call "+p+" due to unbound types",m)}l=l[0];var p=l.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);
h&&l.V.sa.push(b);var r=l.V.da,u=r[b];void 0===u||void 0===u.Y&&u.className!==l.name&&u.ga===c-2?(n.ga=c-2,n.className=l.name,r[b]=n):(wb(r,b,p),r[b].Y[c-2]=n);U([],m,function(t){t=Lb(p,t,l,f,k);void 0===r[b].Y?(t.ga=c-2,r[b]=t):r[b].Y[c-2]=t;return[]});return[]})},d:function(a,b,c,d,e,f,k,h,m,l){b=O(b);e=Y(d,e);U([],[a],function(n){n=n[0];var p=n.name+"."+b,r={get:function(){Z("Cannot access "+p+" due to unbound types",[c,k])},enumerable:!0,configurable:!0};r.set=m?function(){Z("Cannot access "+
p+" due to unbound types",[c,k])}:function(){N(p+" is a read-only property")};Object.defineProperty(n.V.da,b,r);U([],m?[c,k]:[c],function(u){var t=u[0],w={get:function(){var L=Nb(this,n,p+" getter");return t.fromWireType(e(f,L))},enumerable:!0};if(m){m=Y(h,m);var A=u[1];w.set=function(L){var F=Nb(this,n,p+" setter"),fa=[];m(l,F,A.toWireType(fa,L));ob(fa)}}Object.defineProperty(n.V.da,b,w);return[]});return[]})},J:function(a,b,c){a=O(a);U([],[b],function(d){d=d[0];g[a]=d.fromWireType(c);return[]})},
E:function(a,b){b=O(b);V(a,{name:b,fromWireType:function(c){var d=$a(c);Ob(c);return d},toWireType:function(c,d){return ab(d)},argPackAdvance:8,readValueFromPointer:pb,aa:null})},i:function(a,b,c,d){function e(){}c=tb(c);b=O(b);e.values={};V(a,{name:b,constructor:e,fromWireType:function(f){return this.constructor.values[f]},toWireType:function(f,k){return k.value},argPackAdvance:8,readValueFromPointer:Pb(b,c,d),aa:null});xb(b,e)},e:function(a,b,c){var d=jb(a,"enum");b=O(b);a=d.constructor;d=Object.create(d.constructor.prototype,
{value:{value:c},constructor:{value:Xa(d.name+"_"+b,function(){})}});a.values[c]=d;a[b]=d},x:function(a,b,c){c=tb(c);b=O(b);V(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:Qb(b,c),aa:null})},k:function(a,b,c,d,e,f){var k=Mb(b,c);a=O(a);e=Y(d,e);xb(a,function(){Z("Cannot call "+a+" due to unbound types",k)},b-1);U([],k,function(h){h=[h[0],null].concat(h.slice(1));Ib(a,Lb(a,h,null,e,f),b-1);return[]})},o:function(a,b,c,d,e){function f(h){return h}
b=O(b);-1===e&&(e=4294967295);e=tb(c);if(0===d){var k=32-8*c;f=function(h){return h<<k>>>k}}c=b.includes("unsigned")?function(h,m){return m>>>0}:function(h,m){return m};V(a,{name:b,fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:Rb(b,e,0!==d),aa:null})},j:function(a,b,c){function d(f){f>>=2;var k=H;return new e(G,k[f+1],k[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=O(c);V(a,{name:c,fromWireType:d,argPackAdvance:8,
readValueFromPointer:d},{Da:!0})},w:function(a,b){b=O(b);var c="std::string"===b;V(a,{name:b,fromWireType:function(d){var e=H[d>>2];if(c)for(var f=d+4,k=0;k<=e;++k){var h=d+4+k;if(k==e||0==C[h]){f=f?ta(C,f,h-f):"";if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=h+1}}else{m=Array(e);for(k=0;k<e;++k)m[k]=String.fromCharCode(C[d+4+k]);m=m.join("")}R(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||
e instanceof Uint8ClampedArray||e instanceof Int8Array||N("Cannot pass non-string to std::string");var k=(c&&f?function(){for(var l=0,n=0;n<e.length;++n){var p=e.charCodeAt(n);55296<=p&&57343>=p&&(p=65536+((p&1023)<<10)|e.charCodeAt(++n)&1023);127>=p?++l:l=2047>=p?l+2:65535>=p?l+3:l+4}return l}:function(){return e.length})(),h=ac(4+k+1);H[h>>2]=k;if(c&&f)ua(e,h+4,k+1);else if(f)for(f=0;f<k;++f){var m=e.charCodeAt(f);255<m&&(R(h),N("String has UTF-16 code units that do not fit in 8 bits"));C[h+4+f]=
m}else for(f=0;f<k;++f)C[h+4+f]=e[f];null!==d&&d.push(R,h);return h},argPackAdvance:8,readValueFromPointer:pb,aa:function(d){R(d)}})},s:function(a,b,c){c=O(c);if(2===b){var d=wa;var e=ya;var f=za;var k=function(){return xa};var h=1}else 4===b&&(d=Aa,e=Ba,f=Ca,k=function(){return H},h=2);V(a,{name:c,fromWireType:function(m){for(var l=H[m>>2],n=k(),p,r=m+4,u=0;u<=l;++u){var t=m+4+u*b;if(u==l||0==n[t>>h])r=d(r,t-r),void 0===p?p=r:(p+=String.fromCharCode(0),p+=r),r=t+b}R(m);return p},toWireType:function(m,
l){"string"!==typeof l&&N("Cannot pass non-string to C++ string type "+c);var n=f(l),p=ac(4+n+b);H[p>>2]=n>>h;e(l,p+4,n+b);null!==m&&m.push(R,p);return p},argPackAdvance:8,readValueFromPointer:pb,aa:function(m){R(m)}})},n:function(a,b,c,d,e,f){nb[a]={name:O(b),oa:Y(c,d),ea:Y(e,f),ra:[]}},g:function(a,b,c,d,e,f,k,h,m,l){nb[a].ra.push({xa:O(b),Ca:c,Aa:Y(d,e),Ba:f,Ia:k,Ha:Y(h,m),Ja:l})},G:function(a,b){b=O(b);V(a,{Ea:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},q:function(a,
b,c,d){a=Tb[a];b=$a(b);var e=Sb[c];c=void 0===e?O(c):e;a(b,c,null,d)},p:Ob,r:function(a,b){var c=Vb(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(k){return k.name}).join("_")+"$";var e=Wb[b];if(void 0!==e)return e;var f=Array(a-1);e=Ub(function(k,h,m,l){for(var n=0,p=0;p<a-1;++p)f[p]=c[p+1].Oa(l+n),n+=c[p+1].La;k=k[h].apply(k,f);for(p=0;p<a-1;++p)c[p+1].va&&c[p+1].va(f[p]);if(!d.Ea)return d.toWireType(m,k)});return Wb[b]=e},y:function(a){4<a&&(K[a].pa+=1)},l:function(a,b){a=jb(a,"_emval_take_value");
a=a.readValueFromPointer(b);return ab(a)},h:function(){z("")},u:Xb,B:function(a,b,c){C.copyWithin(a,b,b+c)},C:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{B.grow(Math.min(2147483648,d)-G.byteLength+65535>>>16);Ga(B.buffer);var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},D:function(a){if(!(noExitRuntime||0<pa)){if(g.onExit)g.onExit(a);ra=!0}ea(a,new oa(a))},
v:function(a,b,c,d){for(var e=0,f=0;f<c;f++){var k=E[b>>2],h=E[b+4>>2];b+=8;for(var m=0;m<h;m++){var l=C[k+m],n=Yb[a];0===l||10===l?((1===a?qa:x)(ta(n,0)),n.length=0):n.push(l)}e+=h}E[d>>2]=e;return 0},H:function(a){var b=Date.now();E[a>>2]=b/1E3|0;E[a+4>>2]=b%1E3*1E3|0;return 0},a:B,t:function(){}};
(function(){function a(e){g.asm=e.exports;Ia=g.asm.N;Ka.unshift(g.asm.K);I--;g.monitorRunDependencies&&g.monitorRunDependencies(I);0==I&&(null!==Na&&(clearInterval(Na),Na=null),Oa&&(e=Oa,Oa=null,e()))}function b(e){a(e.instance)}function c(e){return Sa().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){x("failed to asynchronously prepare wasm: "+f);z(f)})}var d={a:bc};I++;g.monitorRunDependencies&&g.monitorRunDependencies(I);if(g.instantiateWasm)try{return g.instantiateWasm(d,
a)}catch(e){return x("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return y||"function"!==typeof WebAssembly.instantiateStreaming||Pa()||J.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(J,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){x("wasm streaming compile failed: "+f);x("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ca);return{}})();
g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.K).apply(null,arguments)};var ac=g._malloc=function(){return(ac=g._malloc=g.asm.L).apply(null,arguments)},R=g._free=function(){return(R=g._free=g.asm.M).apply(null,arguments)},ib=g.___getTypeName=function(){return(ib=g.___getTypeName=g.asm.O).apply(null,arguments)};g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.P).apply(null,arguments)};
g.dynCall_iijii=function(){return(g.dynCall_iijii=g.asm.Q).apply(null,arguments)};g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.R).apply(null,arguments)};g.dynCall_vifijiif=function(){return(g.dynCall_vifijiif=g.asm.S).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.T).apply(null,arguments)};var cc;function oa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Oa=function dc(){cc||ec();cc||(Oa=dc)};
function ec(){function a(){if(!cc&&(cc=!0,g.calledRun=!0,!ra)){Ta(Ka);ba(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();La.unshift(b)}Ta(La)}}if(!(0<I)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ma();Ta(Ja);0<I||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=ec;
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();ec();


  return PHYSX.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = PHYSX;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return PHYSX; });
else if (typeof exports === 'object')
  exports["PHYSX"] = PHYSX;


var _PHYSX_Module = PHYSX;
var _initialMemory = 0;

// 包装模块：在调用原始模块前，检查并添加 INITIAL_MEMORY 到 moduleArg
var _wrappedModule = function(moduleArg) {
    if (_initialMemory) {
        moduleArg["INITIAL_MEMORY"] = _initialMemory * 65536;
    }
    return _PHYSX_Module(moduleArg);
};

// 使用 WasmAdapter.create 创建加载器（在文件加载时执行，正确捕获 webDir）
var _PHYSX_Loader = Laya.WasmAdapter.create(_wrappedModule);

window.PHYSX = function(initialMemory, interactive) {
    _initialMemory = initialMemory || 0;
    return _PHYSX_Loader();
};
}