import { ClassUtils } from "../utils/ClassUtils";
import { AdvImage } from "./AdvImage";
import { AutoBitmap } from "./AutoBitmap";
import { Box } from "./Box";
import { Button } from "./Button";
import { CheckBox } from "./CheckBox";
import { Clip } from "./Clip";
import { ColorPicker } from "./ColorPicker";
import { ComboBox } from "./ComboBox";
import { Dialog } from "./Dialog";
import { DialogManager } from "./DialogManager";
import { FontClip } from "./FontClip";
import { HBox } from "./HBox";
import { HScrollBar } from "./HScrollBar";
import { HSlider } from "./HSlider";
import { Image } from "./Image";
import { Label } from "./Label";
import { LayoutBox } from "./LayoutBox";
import { List } from "./List";
import { Panel } from "./Panel";
import { ProgressBar } from "./ProgressBar";
import { Radio } from "./Radio";
import { RadioGroup } from "./RadioGroup";
import { ScaleBox } from "./ScaleBox";
import { ScrollBar } from "./ScrollBar";
import { Slider } from "./Slider";
import { Tab } from "./Tab";
import { TextArea } from "./TextArea";
import { TextInput } from "./TextInput";
import { TipManager } from "./TipManager";
import { Tree } from "./Tree";
import { UIComponent } from "./UIComponent";
import { UIEvent } from "./UIEvent";
import { UIGroup } from "./UIGroup";
import { UIUtils } from "./UIUtils";
import { VBox } from "./VBox";
import { View } from "./View";
import { ViewStack } from "./ViewStack";
import { VScrollBar } from "./VScrollBar";
import { VSlider } from "./VSlider";
import { Widget } from "./Widget";
import { WXOpenDataViewer } from "./WXOpenDataViewer";

let c = ClassUtils.regClass;
c("Laya.AdvImage", AdvImage);
c("Laya.AutoBitmap", AutoBitmap);
c("Laya.Box", Box);
c("Laya.Button", Button);
c("Laya.CheckBox", CheckBox);
c("Laya.Clip", Clip);
c("Laya.ColorPicker", ColorPicker);
c("Laya.ComboBox", ComboBox);
c("Laya.Dialog", Dialog);
c("Laya.DialogManager", DialogManager);
c("Laya.FontClip", FontClip);
c("Laya.HBox", HBox);
c("Laya.HScrollBar", HScrollBar);
c("Laya.HSlider", HSlider);
c("Laya.Image", Image);
c("Laya.Label", Label);
c("Laya.LayoutBox", LayoutBox);
c("Laya.List", List);
c("Laya.Panel", Panel);
c("Laya.ProgressBar", ProgressBar);
c("Laya.Radio", Radio);
c("Laya.RadioGroup", RadioGroup);
c("Laya.ScaleBox", ScaleBox);
c("Laya.ScrollBar", ScrollBar);
c("Laya.Slider", Slider);
c("Laya.Tab", Tab);
c("Laya.TextArea", TextArea);
c("Laya.TextInput", TextInput);
c("Laya.TipManager", TipManager);
c("Laya.Tree", Tree);
c("Laya.UIGroup", UIGroup);
c("Laya.UIUtils", UIUtils);
c("Laya.VBox", VBox);
c("Laya.View", View);
c("Laya.ViewStack", ViewStack);
c("Laya.VScrollBar", VScrollBar);
c("Laya.VSlider", VSlider);
c("Laya.Widget", Widget);
c("Laya.UIComponent", UIComponent);
c("Laya.UIEvent", UIEvent);

c("Laya.WXOpenDataViewer", WXOpenDataViewer);