import { ILaya } from "../../ILaya";
import { Node } from "../display/Node";
import { Loader } from "../net/Loader";
import { Resource } from "./Resource";

/**
 * @en Prefab class.
 * @zh 预制体类。
 */
export class Prefab extends Resource {
    /**
     * @en Whether the prefab is generated by the DCC tool.
     * @zh 预制体是否是由 DCC 工具生成的。
     */
    fromDCC: boolean = false;

    /**
     * @ignore @blueprintIgnore
     */
    constructor() {
        super(false);

        this._traceDeps = true;
    }

    /**
     * @en If the prefab is loaded from a url, call this method to enable management of the prefab by the resource manager.
     * @zh 如果预制体是从 URL 加载的，则调用此方法以启用资源管理器对预制体的管理。
     */
    onLoad(): this {
        Resource._idResourcesMap[this._id] = this;
        return this;
    }

    /**
     * @en Create an instance of the prefab.
     * @param options Instantiation options.
     * @param errors Error content.
     * @zh 创建一个预制体的实例。
     * @param options 实例化选项
     * @param errors 错误内容
     */
    create(options?: Record<string, any>, errors?: Array<any>): Node {
        return null;
    }

    /**
     * @en Instantiate a prefab from a URL.
     * @param url The URL of the prefab.
     * @param classType Optional child node type, used to specify the type of the returned child node.
     * @zh 从 URL 实例化一个预制体。
     * @param url 预制体的 URL。
     * @param classType 可选的节点类型，用于明确返回节点的类型。
     * @returns A promise that resolves to the instantiated Node. 
     */
    static instantiate<T extends Node>(url: string, classType?: new () => T): Promise<T> {
        return ILaya.loader.load(url, Loader.HIERARCHY).then((res: Prefab) => {
            return res.create() as T;
        });
    }
}

//旧版本兼容
export type HierarchyResource = Prefab;
export var HierarchyResource = Prefab;